file_format: "1"
id: crowkb_38
name: crowkb_38
type: shield
url: https://github.com/c-botz/crokb
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - crowkb_38_left
  - crowkb_38_right